/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'tutorials/quickstart', {
      type: 'link',
      label: 'Q&A', // 链接标签
      href: 'https://github.com/eva-engine/eva.js/issues/140', // 外部 URL
    },
    {
      type: 'category',
      label: 'Basic',
      collapsible: true,
      collapsed: false,
      items: ['tutorials/resourceManagement',
        'tutorials/game',
        'tutorials/gameObject',
        'tutorials/transformComponent',
        'tutorials/compressedTexture']
    },
    {
      type: 'category',
      label: 'Graphics',
      collapsible: true,
      collapsed: false,
      items: ['tutorials/prepareRender',
        'tutorials/imageComponent',
        'tutorials/textComponent',
        'tutorials/graphicsComponent',
        'tutorials/spriteComponent',
        'tutorials/maskComponent',
        'tutorials/ninePatchComponent',
        'tutorials/tilingSpriteComponent',
        'tutorials/orderAndTransparent']
    },
    {
      type: 'category',
      label: 'Animation',
      collapsible: true,
      collapsed: false,
      items: ['tutorials/transitionAnimation',
        'tutorials/spriteAnimation',
        'tutorials/spineAnimation',
        'tutorials/dragonboneAnimation',
        'tutorials/lottieAnimation',
        'tutorials/interactionEvent',
        'tutorials/customComponent']
    },
    {
      type: 'category',
      label: 'Plugin',
      collapsible: true,
      collapsed: false,
      items: ['tutorials/sound',
        'tutorials/matterJS',
        'tutorials/a11yPlugin',
        'tutorials/evaxPlugin',
        'tutorials/performancePlugin',
        'tutorials/pluginDevelop']
    },
    {
      type: 'category',
      label: 'Others',
      collapsible: true,
      collapsed: false,
      items: ['tutorials/cdnIntro']
    }
  ],
  apiSidebar: [
    'api/index',
    'api/eva.js',
    {
      type: 'category', label: 'renderer', items: [
        'api/eva-plugin-renderer',
        'api/eva-plugin-renderer-dragonbone',
        'api/eva-plugin-renderer-event',
        'api/eva-plugin-renderer-graphics',
        'api/eva-plugin-renderer-img',
        'api/eva-plugin-renderer-mask',
        'api/eva-plugin-renderer-nine-patch',
        'api/eva-plugin-renderer-spine',
        'api/eva-plugin-renderer-sprite',
        'api/eva-plugin-renderer-sprite-animation',
        'api/eva-plugin-renderer-text',
        'api/eva-plugin-renderer-tiling-sprite',
        'api/eva-plugin-renderer-render',
        'api/eva-renderer-adapter',
      ]
    },
    'api/eva-plugin-evax',
    'api/eva-plugin-stats',
    'api/eva-plugin-transition',
    // 'api/eva-miniprogram-pixi',
    // 'api/eva-miniprogram-adapter'
  ],
};

module.exports = sidebars;
